language: c++

git:
  depth: 1

dist: trusty

sudo: true

install:
 - echo "deb http://de.archive.ubuntu.com/ubuntu xenial main restricted universe multiverse" | sudo tee -a /etc/apt/sources.list
 - sudo apt-get update
 - sudo apt-get install --allow-unauthenticated g++ libboost-all-dev cmake libreadline-dev libssl-dev autoconf

script:
 - cmake -DCMAKE_BUILD_TYPE=Debug -DBoost_USE_STATIC_LIBS=OFF .
 - make -j 2
 
 deploy:
     provider: releases
     api_key:
         secure: <your key>
     file: 
         - cli-wallet
         - delayed_node
         - witness_node
     skip_cleanup: true
     draft: true
     on:
         repo: ryanrfox/bitshares-core
         tags: true
